language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage
  - python setup.py install

script:
  - coverage run -m unittest

after_success:
  - bash <(curl -s https://codecov.io/bash)
